/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AscSortIcon: typeof import('./src/components/icons/AscSortIcon.vue')['default']
    BackButton: typeof import('./src/components/buttons/BackButton.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Box: typeof import('./src/components/UI/Box.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckBoxField: typeof import('./src/components/form/CheckBoxField.vue')['default']
    ClearFilters: typeof import('./src/components/buttons/ClearFilters.vue')['default']
    DarkModeIcon: typeof import('./src/components/icons/DarkModeIcon.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/DashboardIcon.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DatePickerField: typeof import('./src/components/form/DatePickerField.vue')['default']
    DeleteIcon: typeof import('./src/components/icons/DeleteIcon.vue')['default']
    DescSortIcon: typeof import('./src/components/icons/DescSortIcon.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditIcon: typeof import('./src/components/icons/EditIcon.vue')['default']
    ExitIcon: typeof import('./src/components/icons/ExitIcon.vue')['default']
    ExpandIcon: typeof import('./src/components/icons/ExpandIcon.vue')['default']
    EyeFill: typeof import('./src/components/icons/EyeFill.vue')['default']
    EyeOffFill: typeof import('./src/components/icons/EyeOffFill.vue')['default']
    FilterIcon: typeof import('./src/components/icons/FilterIcon.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    IconButton: typeof import('./src/components/buttons/IconButton.vue')['default']
    InfoIcon: typeof import('./src/components/icons/InfoIcon.vue')['default']
    InputPasswordField: typeof import('./src/components/form/InputPasswordField.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InputTextField: typeof import('./src/components/form/InputTextField.vue')['default']
    LightModeIcon: typeof import('./src/components/icons/LightModeIcon.vue')['default']
    LogoIcon: typeof import('./src/components/icons/LogoIcon.vue')['default']
    MainButton: typeof import('./src/components/buttons/MainButton.vue')['default']
    MainDataTable: typeof import('./src/components/table/MainDataTable.vue')['default']
    MainTitle: typeof import('./src/components/UI/MainTitle.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NoSortIcon: typeof import('./src/components/icons/NoSortIcon.vue')['default']
    PagesHeader: typeof import('./src/components/UI/PagesHeader.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RoundedButton: typeof import('./src/components/buttons/RoundedButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowSelect: typeof import('./src/components/table/RowSelect.vue')['default']
    SearchInput: typeof import('./src/components/form/SearchInput.vue')['default']
    SelectBox: typeof import('./src/components/form/SelectBox.vue')['default']
    SpinnerLoading: typeof import('./src/components/UI/SpinnerLoading.vue')['default']
    SuppliersIcon: typeof import('./src/components/icons/SuppliersIcon.vue')['default']
    TextLogoIcon: typeof import('./src/components/icons/TextLogoIcon.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ToggleSwitchButton: typeof import('./src/components/form/ToggleSwitchButton.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
